export const referral = [
  {
    code: 'jinbnb',
    name: '衿日林民宿',
  },{
    code: 'yesbnb',
    name: 'YES民宿',
  },
  { code: 'BNB335', name: '根本町咖啡民宿' },
  { code: 'BNB37L', name: '小Ｋ咖啡b&b民宿' },
  { code: 'BNB3AY', name: '阿爾卑斯' },
  { code: 'BNB3DQ', name: '海田行館' },
  { code: 'BNB3H7', name: '小北歐699' },
  { code: 'BNB3JC', name: '香狄亞民宿' },
  { code: 'BNB3MF', name: '塍畦民宿' },
  { code: 'BNB3QF', name: '漫居民宿' },
  { code: 'BNB3TL', name: 'F1民宿' },
  { code: 'BNB3V6', name: '星宿度假別墅' },
  { code: 'BNB3XD', name: '幸運草庭園民宿' },
  { code: 'BNB45E', name: '衿日林民宿' },
  { code: 'BNB47F', name: '蘆薈villa民宿' },
  { code: 'BNB4DG', name: '135會館' },
  { code: 'BNB4F5', name: '蘭卡威民宿' },
  { code: 'BNB4JX', name: '裏白villa民宿' },
  { code: 'BNB4L6', name: '巴黎左岸' },
  { code: 'BNB4PF', name: '金洙椏民宿' },
  { code: 'BNB4RX', name: 'I DO' },
  { code: 'BNB4TX', name: '四季花園歐風館' },
  { code: 'BNB4XS', name: '寬院子稻禾館' },
  { code: 'BNB53D', name: '遇見山嵐' },
  { code: 'BNB564', name: '蔥境雅閣民宿' },
  { code: 'BNB593', name: '幸福蝸牛' },
  { code: 'BNB5D7', name: '蜜雪蓮城堡民宿' },
  { code: 'BNB5GA', name: '樂山水休閒農園' },
  { code: 'BNB5HN', name: '星果園休閒民宿' },
  { code: 'BNB5ML', name: '貝兒花園民宿' },
  { code: 'BNB5NP', name: '曉翠軒民宿' },
  { code: 'BNB5SN', name: '好望角民宿' },
  { code: 'BNB5VG', name: '玉蘭函館景館民宿' },
  { code: 'BNB5YH', name: '仁山民宿 自由心向' },
  { code: 'BNB63L', name: '靜園休閒民宿' },
  { code: 'BNB66P', name: '雅廬景觀渡假別墅' },
  { code: 'BNB69X', name: '奧羅拉風格民宿' },
  { code: 'BNB6EJ', name: '魚雅築渡假民宿' },
  { code: 'BNB6HL', name: '雨庭宿' },
  { code: 'BNB6KW', name: '好民宿 /雲朵朵' },
  { code: 'BNB6MV', name: '田念民宿' },
  { code: 'BNB6QF', name: '遇而歡田園民宿' },
  { code: 'BNB6SR', name: '老公老婆友善民宿' },
  { code: 'BNB6WP', name: '月桂田民宿/稻邸民宿' },
  { code: 'BNB6X5', name: '星8藝宿' },
  { code: 'BNB73C', name: '禾樂號' },
  { code: 'BNB79F', name: '好自然休閒農場' },
  { code: 'BNB7CY', name: '吳哥villa 會館' },
  { code: 'BNB7D9', name: '珍珠壹伍零' },
  { code: 'BNB7H7', name: '綠寶石休閒農場' },
  { code: 'BNB7KJ', name: '睡海邊民宿' },
  { code: 'BNB7PD', name: '米修B&B' },
  { code: 'BNB7RD', name: '伯利恆之星民宿' },
  { code: 'BNB7S7', name: '小蘋果' },
  { code: 'BNB7XT', name: '安農左岸' },
  { code: 'BNB7Y6', name: '星賞民宿' },
  { code: 'BNB94H', name: '小島villa' },
  { code: 'BNB97F', name: '沐光小院' },
  { code: 'BNB9CT', name: '圓夢屋' },
  { code: 'BNB9ED', name: '鴝花甜點民宿' },
  { code: 'BNB9JK', name: '蘭調villa' },
  { code: 'BNB9KE', name: '世外桃川' },
  { code: 'BNB9NV', name: '135villa' },
  { code: 'BNB9QF', name: '布朗尼' },
  { code: 'BNB9VJ', name: '山聽樹說' },
  { code: 'BNB9WG', name: '首席渡假會館' },
  { code: 'BNBA4D', name: '匯沄居民宿' },
  { code: 'BNBA6T', name: '澍蒔' },
  { code: 'BNBA9W', name: '貓天空鄉村民宿' },
  { code: 'BNBADQ', name: '淞湘卉館' },
  { code: 'BNBAFJ', name: '' },
  { code: 'BNBAKX', name: '' },
  { code: 'BNBAN3', name: '' },
  { code: 'BNBAP6', name: '' },
  { code: 'BNBARS', name: '' },
  { code: 'BNBAUQ', name: '' },
  { code: 'BNBAXJ', name: '' },
  { code: 'BNBC49', name: '' },
  { code: 'BNBC6X', name: '' },
  { code: 'BNBCC4', name: '' },
  { code: 'BNBCEG', name: '' },
  { code: 'BNBCFH', name: '' },
  { code: 'BNBCJU', name: '' },
  { code: 'BNBCNF', name: '' },
  { code: 'BNBCRG', name: '' },
  { code: 'BNBCS4', name: '' },
  { code: 'BNBCWL', name: '' },
  { code: 'BNBD3S', name: '' },
  { code: 'BNBD4Q', name: '' },
  { code: 'BNBD76', name: '' },
  { code: 'BNBDAF', name: '' },
  { code: 'BNBDEK', name: '' },
  { code: 'BNBDG4', name: '' },
  { code: 'BNBDKJ', name: '' },
  { code: 'BNBDP4', name: '' },
  { code: 'BNBDRF', name: '' },
  { code: 'BNBDT6', name: '' },
  { code: 'BNBDWA', name: '' },
  { code: 'BNBE3G', name: '' },
  { code: 'BNBE5X', name: '' },
  { code: 'BNBE79', name: '' },
  { code: 'BNBEDE', name: '' },
  { code: 'BNBEEQ', name: '' },
  { code: 'BNBEJ3', name: '' },
  { code: 'BNBELH', name: '' },
  { code: 'BNBEP7', name: '' },
  { code: 'BNBER9', name: '' },
  { code: 'BNBEU7', name: '' },
  { code: 'BNBEXR', name: '' },
  { code: 'BNBF4S', name: '' },
  { code: 'BNBF5D', name: '' },
  { code: 'BNBF93', name: '' },
  { code: 'BNBFDJ', name: '' },
  { code: 'BNBFFG', name: '' },
  { code: 'BNBFK7', name: '' },
  { code: 'BNBFNU', name: '' },
  { code: 'BNBFQY', name: '' },
  { code: 'BNBFS9', name: '' },
  { code: 'BNBFV6', name: '' },
  { code: 'BNBFXT', name: '' },
  { code: 'BNBG3A', name: '' },
  { code: 'BNBG6H', name: '' },
  { code: 'BNBGCN', name: '' },
  { code: 'BNBGDY', name: '' },
  { code: 'BNBGHC', name: '' },
  { code: 'BNBGLD', name: '' },
  { code: 'BNBGMD', name: '' },
  { code: 'BNBGRD', name: '' },
  { code: 'BNBGUA', name: '' },
  { code: 'BNBGXG', name: '' },
  { code: 'BNBGY9', name: '' },
  { code: 'BNBH53', name: '' },
  { code: 'BNBH94', name: '' },
  { code: 'BNBHAJ', name: '' },
  { code: 'BNBHFT', name: '' },
  { code: 'BNBHJU', name: '' },
  { code: 'BNBHMY', name: '' },
  { code: 'BNBHPA', name: '' },
  { code: 'BNBHQ6', name: '' },
  { code: 'BNBHTX', name: '' },
  { code: 'BNBHWE', name: '' },
  { code: 'BNBJ34', name: '' },
  { code: 'BNBJ57', name: '' },
  { code: 'BNBJ9P', name: '' },
  { code: 'BNBJDH', name: '' },
  { code: 'BNBJGV', name: '' },
  { code: 'BNBJKU', name: '' },
  { code: 'BNBJLX', name: '' },
  { code: 'BNBJPQ', name: '' },
  { code: 'BNBJSW', name: '' },
  { code: 'BNBJUA', name: '' },
  { code: 'BNBJWW', name: '' },
  { code: 'BNBK4D', name: '' },
  { code: 'BNBK7G', name: '' },
  { code: 'BNBK9H', name: '' },
  { code: 'BNBKED', name: '' },
  { code: 'BNBKGP', name: '' },
  { code: 'BNBKKN', name: '' },
  { code: 'BNBKMA', name: '' },
  { code: 'BNBKQV', name: '' },
  { code: 'BNBKTM', name: '' },
  { code: 'BNBKWD', name: '' },
  { code: 'BNBKXX', name: '' },
  { code: 'BNBL59', name: '' },
  { code: 'BNBL7S', name: '' },
  { code: 'BNBLD5', name: '' },
  { code: 'BNBLFV', name: '' },
  { code: 'BNBLJU', name: '' },
  { code: 'BNBLKX', name: '' },
  { code: 'BNBLMH', name: '' },
  { code: 'BNBLSU', name: '' },
  { code: 'BNBLTJ', name: '' },
  { code: 'BNBLWQ', name: '' },
  { code: 'BNBLYJ', name: '' },
  { code: 'BNBM5G', name: '' },
  { code: 'BNBM7D', name: '' },
  { code: 'BNBMCN', name: '' },
  { code: 'BNBMGW', name: '' },
  { code: 'BNBMH6', name: '' },
  { code: 'BNBMLX', name: '' },
  { code: 'BNBMP6', name: '' },
  { code: 'BNBMRF', name: '' },
  { code: 'BNBMU9', name: '' },
  { code: 'BNBMX4', name: '' },
  { code: 'BNBN47', name: '' },
  { code: 'BNBN6H', name: '' },
  { code: 'BNBN93', name: '' },
  { code: 'BNBNDJ', name: '' },
  { code: 'BNBNHQ', name: '' },
  { code: 'BNBNKX', name: '' },
  { code: 'BNBNMX', name: '' },
  { code: 'BNBNQN', name: '' },
  { code: 'BNBNTN', name: '' },
  { code: 'BNBNUF', name: '' },
  { code: 'BNBNX7', name: '' },
  { code: 'BNBP3P', name: '' },
  { code: 'BNBP9T', name: '' },
  { code: 'BNBPAD', name: '' },
  { code: 'BNBPDP', name: '' },
  { code: 'BNBPHA', name: '' },
  { code: 'BNBPJE', name: '' },
  { code: 'BNBPND', name: '' },
  { code: 'BNBPRE', name: '' },
  { code: 'BNBPS5', name: '' },
  { code: 'BNBPV6', name: '' },
  { code: 'BNBPY7', name: '' },
  { code: 'BNBQ4N', name: '' },
  { code: 'BNBQ9V', name: '' },
  { code: 'BNBQDU', name: '' },
  { code: 'BNBQGK', name: '' },
  { code: 'BNBQJS', name: '' },
  { code: 'BNBQKW', name: '' },
  { code: 'BNBQNP', name: '' },
  { code: 'BNBQRK', name: '' },
  { code: 'BNBQTW', name: '' },
  { code: 'BNBQXY', name: '' },
  { code: 'BNBR4U', name: '' },
  { code: 'BNBR5C', name: '' },
  { code: 'BNBRAH', name: '' },
  { code: 'BNBRDA', name: '' },
  { code: 'BNBRFY', name: '' },
  { code: 'BNBRHT', name: '' },
  { code: 'BNBRMJ', name: '' },
  { code: 'BNBRQP', name: '' },
  { code: 'BNBRSC', name: '' },
  { code: 'BNBRU7', name: '' },
  { code: 'BNBRXJ', name: '' },
  { code: 'BNBS4M', name: '' },
  { code: 'BNBS7H', name: '' },
  { code: 'BNBSCW', name: '' },
  { code: 'BNBSDH', name: '' },
  { code: 'BNBSGV', name: '' },
  { code: 'BNBSL3', name: '' },
  { code: 'BNBSMT', name: '' },
  { code: 'BNBSQN', name: '' },
  { code: 'BNBST9', name: '' },
  { code: 'BNBSVC', name: '' },
  { code: 'BNBSYC', name: '' },
  { code: 'BNBT43', name: '' },
  { code: 'BNBT9G', name: '' },
  { code: 'BNBTDC', name: '' },
  { code: 'BNBTFQ', name: '' },
  { code: 'BNBTGQ', name: '' },
  { code: 'BNBTKC', name: '' },
  { code: 'BNBTME', name: '' },
  { code: 'BNBTSU', name: '' },
  { code: 'BNBTTM', name: '' },
  { code: 'BNBTVD', name: '' },
  { code: 'BNBU3Y', name: '' },
  { code: 'BNBU56', name: '' },
  { code: 'BNBU9C', name: '' },
  { code: 'BNBUDT', name: '' },
  { code: 'BNBUFT', name: '' },
  { code: 'BNBUJC', name: '' },
  { code: 'BNBUMT', name: '' },
  { code: 'BNBUPG', name: '' },
  { code: 'BNBUS4', name: '' },
  { code: 'BNBUUQ', name: '' },
  { code: 'BNBUXA', name: '' },
  { code: 'BNBV33', name: '' },
  { code: 'BNBV7M', name: '' },
  { code: 'BNBVAQ', name: '' },
  { code: 'BNBVCG', name: '' },
  { code: 'BNBVG7', name: '' },
  { code: 'BNBVJA', name: '' },
  { code: 'BNBVLS', name: '' },
  { code: 'BNBVPN', name: '' },
  { code: 'BNBVSG', name: '' },
  { code: 'BNBVUK', name: '' },
  { code: 'BNBVYL', name: '' },
  { code: 'BNBW46', name: '' },
  { code: 'BNBW6G', name: '' },
  { code: 'BNBWCW', name: '' },
  { code: 'BNBWDE', name: '' },
  { code: 'BNBWHY', name: '' },
  { code: 'BNBWJA', name: '' },
  { code: 'BNBWM5', name: '' },
  { code: 'BNBWRY', name: '' },
  { code: 'BNBWUQ', name: '' },
  { code: 'BNBWW6', name: '' },
  { code: 'BNBX3D', name: '' },
  { code: 'BNBX5K', name: '' },
  { code: 'BNBX7V', name: '' },
  { code: 'BNBXCX', name: '' },
  { code: 'BNBXED', name: '' },
  { code: 'BNBXJ4', name: '' },
  { code: 'BNBXLF', name: '' },
  { code: 'BNBXN5', name: '' },
  { code: 'BNBXSE', name: '' },
  { code: 'BNBXVR', name: '' },
  { code: 'BNBXW5', name: '' },
  { code: 'BNBY4Y', name: '' },
  { code: 'BNBY6M', name: '' },
  { code: 'BNBYA3', name: '' },
  { code: 'BNBYD4', name: '' },
  { code: 'BNBYGC', name: '' },
  { code: 'BNBYK6', name: '' },
  { code: 'BNBYNL', name: '' },
  { code: 'BNBYQK', name: '' },
  { code: 'BNBYR9', name: '' },
  { code: 'BNBYUW', name: '' },
  { code: 'BNBYY5', name: '' },
  {code:'202536T',name:'好望角民宿'},
  {code:'20253DW',name:'衿日林'},
  {code:'20253FG',name:'靜園休閒民宿'},
  {code:'20253QS',name:'魚雅築渡假民宿'},
  {code:'20253TY',name:'雅廬民宿'},
  {code:'20253YH',name:'巴黎左岸'},
  {code:'20254CP',name:'奧羅拉風格民宿'},
  {code:'20254F6',name:'仁山愛度假民宿'},
  {code:'20254KH',name:'金洙椏民宿'},
  {code:'20254UY',name:'阿爾卑斯莊園'},
  {code:'20254YF',name:'米修B&B'},
  {code:'2025546',name:'安農左岸民宿'},
  {code:'20255GQ',name:'星賞民宿'},
  {code:'20255J6',name:'田念民宿'},
  {code:'20255NG',name:'塍畦民宿'},
  {code:'20255TE',name:'幸運草庭園民宿'},
  {code:'202564L',name:'貝兒花園民宿'},
  {code:'202569A',name:'蘭卡威民宿'},
  {code:'20256F9',name:'貓天空'},
  {code:'20256P7',name:'老公老婆友善民宿'},
  {code:'20256VY',name:'幸福蝸牛'},
  {code:'20256YU',name:'伯利恆之星'},
  {code:'2025764',name:'首席渡假村民宿'},
  {code:'20257HN',name:'布朗尼民宿'},
  {code:'20257P6',name:'F1民宿'},
  {code:'20257TW',name:'小蘋果'},
  {code:'20257V9',name:'I DO民宿'},
  {code:'202596Q',name:'香狄亞民宿'},
  {code:'20259DK',name:'地熱米休閒民宿'},
  {code:'20259KU',name:'小島民宿'},
  {code:'20259NN',name:'匯沄居'},
  {code:'20259XR',name:'曉翠軒民宿'},
  {code:'20259YR',name:'綠寶石休閒農場'},
  {code:'2025ADY',name:'蜜雪蓮民宿（原喜相逢）'},
  {code:'2025AJA',name:'睡海邊民宿'},
  {code:'2025AQ6',name:'星果園休閒民宿'},
  {code:'2025AUD',name:'小北歐699'},
  {code:'2025AWA',name:'星8藝宿'},
  {code:'2025C9K',name:'小Ｋ咖啡b&b民宿'},
  {code:'2025CEF',name:'樂山水'},
  {code:'2025CNL',name:'寬院子稻禾館'},
  {code:'2025CQE',name:'吳哥villa會館'},
  {code:'2025D3U',name:'澍蒔'},
  {code:'2025D5K',name:'淞湘卉館'},
  {code:'2025DAC',name:'玉蘭函館景觀民宿'},
  {code:'2025DJQ',name:'禾樂號'},
  {code:'2025DR4',name:'漫居民宿'},
  {code:'2025DWL',name:'裏白Villa'},
  {code:'2025DYL',name:'根本町民宿'},
  {code:'2025ECS',name:'珍珠壹伍零'},
  {code:'2025EJR',name:'月桂田民宿'},
  {code:'2025EQ4',name:'山聽樹說'},
  {code:'2025EU7',name:'135會館'},
  {code:'2025F4L',name:'135villa'},
  {code:'2025FAX',name:'鴝花甜點民宿'},
  {code:'2025FDC',name:'遇見山嵐'},
  {code:'2025FKY',name:'蔥境雅閣民宿'},
  {code:'2025FPH',name:'沐光小院'},
  {code:'2025FYF',name:'安語Villa民宿'},
  {code:'2025G5M',name:'蘭調villa'},
  {code:'2025GAG',name:'甜瓜Villa（原本：蘆薈villa'},
  {code:'2025GKN',name:'烤友社宜蘭店'},
  {code:'2025GNT',name:'啡兒咖啡'},
  {code:'2025GVP',name:'五星級飯店用品有限公司'},
  {code:'2025H3J',name:'好自然休閒農場'},
  {code:'2025HAS',name:'旭翔傢飾館'},
  {code:'2025HH3',name:'調到你家去'},
  {code:'2025HN3',name:'青出宜蘭'},
  {code:'2025HQE',name:'炭少年-職人代烤'},
  {code:'2025HW6',name:'究淨宣研'},
  {code:'2025J7S',name:'東昇傢俱'},
  {code:'2025JGM',name:'阿勝哉的-芋香米'},
  {code:'2025JNK',name:'陳億-遊戲活動'},
  {code:'2025JQ3',name:'億大專業洗衣廠'},
  {code:'2025JUK',name:'行銷顧問：江仕超'},
  {code:'2025K7X',name:'冬山鄉鄉民代表'},
  {code:'2025KCF',name:'魔術師'},
  {code:'2025KKN',name:'三星鄉長'},
  {code:'2025KQC',name:'鉄支路早午餐'},
  {code:'2025KW4',name:'東昇咖啡備品'},
  {code:'2025L4M',name:'浪宜夏'},
  {code:'2025L9J',name:''},
  {code:'2025LGX',name:''},
  {code:'2025LNF',name:''},
  {code:'2025LTF',name:''},
  {code:'2025LXM',name:''},
  {code:'2025M9V',name:''},
  {code:'2025MEE',name:''},
  {code:'2025MLJ',name:''},
  {code:'2025MPE',name:''},
  {code:'2025MVY',name:''},
  {code:'2025N7D',name:''},
  {code:'2025NCN',name:''},
  {code:'2025NKD',name:''},
  {code:'2025NMM',name:''},
  {code:'2025NTR',name:''},
  {code:'2025P43',name:''},
  {code:'2025P69',name:''},
  {code:'2025PDP',name:''},
  {code:'2025PPC',name:''},
  {code:'2025PR6',name:''},
  {code:'2025Q3H',name:''},
  {code:'2025Q4Q',name:''},
  {code:'2025QC9',name:''},
  {code:'2025QHC',name:''},
  {code:'2025QRP',name:''},
  {code:'2025QWC',name:''},
  {code:'2025R6M',name:''},
  {code:'2025R9P',name:''},
  {code:'2025RFT',name:''},
  {code:'2025RLA',name:''},
  {code:'2025RUF',name:''},
  {code:'2025RWV',name:''},
  {code:'2025S7G',name:''},
  {code:'2025SH3',name:''},
  {code:'2025SJX',name:''},
  {code:'2025STV',name:''},
  {code:'2025T3X',name:''},
  {code:'2025T5P',name:''},
  {code:'2025TEV',name:''},
  {code:'2025TG7',name:''},
  {code:'2025TNR',name:''},
  {code:'2025TVT',name:''},
  {code:'2025U6N',name:''},
  {code:'2025UDR',name:''},
  {code:'2025UE9',name:''},
  {code:'2025UPN',name:''},
  {code:'2025UTH',name:''},
  {code:'2025UWG',name:''},
  {code:'2025V9S',name:''},
  {code:'2025VGE',name:''},
  {code:'2025VMG',name:''},
  {code:'2025VT9',name:''},
  {code:'2025VU7',name:''},
  {code:'2025W4A',name:''},
  {code:'2025WCP',name:''},
  {code:'2025WG5',name:''},
  {code:'2025WQH',name:''},
  {code:'2025WS7',name:''},
  {code:'2025X5N',name:''},
  {code:'2025XCC',name:''},
  {code:'2025XHL',name:''},
  {code:'2025XNR',name:''},
  {code:'2025XTQ',name:''},
  {code:'2025Y3C',name:''},
  {code:'2025YAT',name:''},
  {code:'2025YGP',name:''},
  {code:'2025YMG',name:''},
  {code:'2025YRH',name:''},
  {code:'2025YWE',name:''}
]
